---
# tasks file for roles/launch_database

- name: Create db container and connect to network
  docker_container:
    name: database
    image: lvcascds/tp-devops:database
    networks:
      - name: app-network
    env: 
      POSTGRES_DB: db
      POSTGRES_USER: usr 
      POSTGRES_PASSWORD: pwd

