---
# tasks file for roles/launch_proxy

# On créé un conteneur appelé httpd en se basant sur notre image hhtpd publique sur dockerhub
# Puis on fait notre redirection de port pour rendre accessible notre appli qui tourne dans docker
# Puis on met notre conteneur dans notre network créé par un autre role
- name: Create proxy container and connect to network
  docker_container:
    name: httpd
    image: lvcascds/tp-devops:httpd
    networks:
      - name: app-network
    ports: 
      - 80:80