---
# tasks file for roles/launch_proxy

- name: Create proxy container and connect to network
  docker_container:
    name: httpd
    image: lvcascds/tp-devops:httpd
    networks:
      - name: app-network